### ISSUE TITLE
[Map] Flur Sek 2 Trakt

### ISSUE THREAD

**Issue by fsoel** [lmg-anrath/workadventure-map#15]
- [x] Basic structure
- [x] First tile design
- [x] Clean Up
- [x]  Game logic
- [ ] Collisions
- [ ] Fine tuning

**Comment by JH220** [comment]
What's the status here? Is the map already finished? @fsoel

**Comment by JH220** [comment]
Hey @fsoel, kannst du noch die Kollisionen und Zonen für den Sek 2 Trakt bis Sonntag 17 Uhr machen? LG

**Comment by fsoel** [comment]
TODO:

-  Kollision nicht perfekt, man kann oft durch Wände laufen 😔
-  Große Treppe braucht noch Tiles

**Comment by JH220** [comment]
TODOs in #29
