### ISSUE TITLE
[Map] IF1 Fachraum

### ISSUE THREAD

**Issue by JH220** [lmg-anrath/workadventure-map#17]
- [x] Basic structure
- [x] First tile design
- [x] Clean Up
- [x]  Game logic
- [x] Collisions
- [ ] Fine tuning

**Comment by JH220** [comment]
Status? @fsoel

**Comment by fsoel** [comment]
TODO:

- Tileset an Stellen überarbeiten
- Whiteboard braucht besseres Tileset

**Comment by JH220** [comment]
TODOs in #30
