### ISSUE TITLE
[Homepage] Website-Design via GitHub Pages

### ISSUE THREAD

**Issue by JH220** [lmg-anrath/workadventure-map#31]

**Comment by JH220** [comment]
@m1kx Please add a
simple home page with
- redirection link to https://play.workadventure-lmg.de for playing,
- redirection link to our school homepage article for more information
- and basic information about our project

**Comment by m1kx** [comment]
@JH220
Die (noch nicht fertige) Seite ist auf lmg-anrath.github.io gehostet, willst du die auf dem Link lassen oder irgendwie in die workadventure-lmg.de Domain einbinden?

**Comment by JH220** [comment]
Hey @m1kx, sieht sehr gut aus.
Die WorkAdventure-Webseite ist bereits unter GitHub gehostet. Allerdings sind dort noch andere SVG-Files und Assets gehostet.
https://github.com/lmg-anrath/workadventure-website
Kannst du die einfach mit in deine Webseite mit einbinden? Dann kannst du die Repo einfach nehmen. Also verknüpft auf unsere GitHub-Organisation ist die auf jeden Fall schon.

**Comment by JH220** [comment]
Ich weiß nicht genau ob das geht. Glaube das sind nicht nur Static-Files sondern auch ein paar Scripts. Entweder du bekommst die in dein Projekt irgendwie integriert oder wir verschieben seine Seite einfach auf eine Subdomain.
